// examples/react-demo/src/App.jsx
import { useState } from 'react'
import useGoFetch from './hooks/useGoFetch'

function App() {
  const { isLoading, error, gofetch, logs, clearLogs } = useGoFetch()
  const [stats, setStats] = useState({ requests: 0, successes: 0, errors: 0 })

  const updateStats = (success) => {
    setStats(prev => ({
      requests: prev.requests + 1,
      successes: success ? prev.successes + 1 : prev.successes,
      errors: success ? prev.errors : prev.errors + 1
    }))
  }

  const handleGetUsers = async () => {
    try {
      const response = await gofetch.get('/users')
      console.log('Users:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error fetching users:', err)
      updateStats(false)
    }
  }

  const handleGetUser = async () => {
    try {
      const response = await gofetch.get('/users/1')
      console.log('User:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error fetching user:', err)
      updateStats(false)
    }
  }

  const handleCreatePost = async () => {
    try {
      const newPost = {
        userId: 1,
        title: 'GoFetch React Demo',
        body: 'This post was created using GoFetch in a React application!'
      }
      
      const response = await gofetch.post('/posts', null, newPost)
      console.log('Created post:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error creating post:', err)
      updateStats(false)
    }
  }

  const handleGetPosts = async () => {
    try {
      const response = await gofetch.get('/posts', { userId: 1 })
      console.log('Posts:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error fetching posts:', err)
      updateStats(false)
    }
  }

  const handleUpdatePost = async () => {
    try {
      const updatedPost = {
        userId: 1,
        id: 1,
        title: 'Updated Title',
        body: 'Updated content from GoFetch!'
      }
      
      const response = await gofetch.put('/posts/1', null, updatedPost)
      console.log('Updated post:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error updating post:', err)
      updateStats(false)
    }
  }

  const handleDeletePost = async () => {
    try {
      const response = await gofetch.delete('/posts/1')
      console.log('Deleted post:', response)
      updateStats(true)
    } catch (err) {
      console.error('Error deleting post:', err)
      updateStats(false)
    }
  }

  const handleWithCustomClient = async () => {
    try {
      // Create a new client instance with custom configuration
      const customClient = gofetch.newClient()
      customClient.setBaseURL('https://jsonplaceholder.typicode.com')
      customClient.setTimeout(5000)
      customClient.setHeader('X-Custom-Header', 'React-Demo')
      
      const response = await customClient.get('/todos/1')
      console.log('Custom client response:', response.data)
      updateStats(true)
    } catch (err) {
      console.error('Error with custom client:', err)
      updateStats(false)
    }
  }

  if (isLoading) {
    return (
      <div className="container">
        <div className="loading">
          <h2>🔄 Loading GoFetch WASM Module...</h2>
          <p>Please wait while we initialize the WebAssembly module.</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container">
        <div className="error">
          <h2>❌ Failed to Load GoFetch</h2>
          <p>{error}</p>
          <p>Make sure you've built the WASM module by running: <code>npm run build:wasm</code></p>
        </div>
      </div>
    )
  }

  return (
    <div className="container">
      <h1>🚀 GoFetch React Demo</h1>
      <p className="subtitle">
        A demonstration of GoFetch HTTP client running in React via WebAssembly
      </p>

      <div className="stats">
        <div className="stat-card">
          <div className="stat-value">{stats.requests}</div>
          <div className="stat-label">Total Requests</div>
        </div>
        <div className="stat-card">
          <div className="stat-value">{stats.successes}</div>
          <div className="stat-label">Successful</div>
        </div>
        <div className="stat-card">
          <div className="stat-value">{stats.errors}</div>
          <div className="stat-label">Errors</div>
        </div>
      </div>

      <div className="controls">
        <button onClick={handleGetUsers}>Get All Users</button>
        <button onClick={handleGetUser}>Get User by ID</button>
        <button onClick={handleGetPosts}>Get User Posts</button>
        <button onClick={handleCreatePost}>Create Post</button>
        <button onClick={handleUpdatePost}>Update Post</button>
        <button onClick={handleDeletePost}>Delete Post</button>
        <button onClick={handleWithCustomClient}>Custom Client</button>
        <button onClick={clearLogs} style={{ marginLeft: 'auto' }}>Clear Logs</button>
      </div>

      <div className="output">
        <h3>Request Logs:</h3>
        {logs.length === 0 ? (
          <p style={{ color: '#666', fontStyle: 'italic' }}>
            No requests yet. Click a button above to make a request.
          </p>
        ) : (
          logs.map((log, index) => (
            <div key={index} className="log-entry">
              <span className="log-timestamp">{log.timestamp}</span>
              <span className={`log-${log.type}`}>{log.message}</span>
              {log.data && (
                <pre>{JSON.stringify(log.data, null, 2)}</pre>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  )
}

export default App

// examples/vue-demo/src/App.vue
<template>
  <div id="app">
    <header>
      <h1>🚀 GoFetch WASM Demo (Vue)</h1>
      <p>A Go HTTP client compiled to WebAssembly, running in your browser!</p>
    </header>

    <div v-if="isLoading" class="loading">
      <div class="spinner"></div>
      <p>Loading GoFetch WASM...</p>
    </div>

    <div v-else-if="error" class="error">
      <h2>❌ Error Loading GoFetch</h2>
      <p>{{ error }}</p>
    </div>

    <div v-else class="container">
      <!-- Request Tester -->
      <div class="card">
        <h2>🧪 Test Requests</h2>
        
        <div class="button-group">
          <button @click="fetchUser" class="btn btn-primary">
            GET /users/1
          </button>
          <button @click="fetchUsers" class="btn btn-info">
            GET /users
          </button>
          <button @click="createPost" class="btn btn-success">
            POST /posts
          </button>
          <button @click="updatePost" class="btn btn-warning">
            PUT /posts/1
          </button>
          <button @click="deletePost" class="btn btn-danger">
            DELETE /posts/1
          </button>
        </div>
      </div>

      <!-- Response Display -->
      <div v-if="currentResponse" class="card">
        <h2>📦 Response</h2>
        <div class="response">
          <div class="response-meta">
            <span class="badge">Status: {{ currentResponse.statusCode }}</span>
          </div>
          <pre class="response-body">{{ JSON.stringify(currentResponse.data, null, 2) }}</pre>
        </div>
      </div>

      <!-- Logs -->
      <div class="card">
        <div class="logs-header">
          <h2>📋 Request Logs</h2>
          <button @click="clearLogs" class="btn btn-small">Clear Logs</button>
        </div>
        
        <div class="logs">
          <div 
            v-for="(log, index) in logs" 
            :key="index" 
            :class="['log-entry', `log-${log.type}`]"
          >
            <span class="log-time">{{ log.timestamp }}</span>
            <span class="log-message">{{ log.message }}</span>
            <pre v-if="log.data" class="log-data">{{ JSON.stringify(log.data, null, 2) }}</pre>
          </div>
          <div v-if="logs.length === 0" class="empty-logs">
            No logs yet. Try making a request!
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useGoFetch } from './composables/useGoFetch.js'

const { isLoading, error, gofetch, logs, clearLogs } = useGoFetch()
const currentResponse = ref(null)

const fetchUser = async () => {
  try {
    const response = await gofetch.value.get('/users/1')
    currentResponse.value = response
  } catch (err) {
    console.error('Request failed:', err)
  }
}

const fetchUsers = async () => {
  try {
    const response = await gofetch.value.get('/users', { _limit: 5 })
    currentResponse.value = response
  } catch (err) {
    console.error('Request failed:', err)
  }
}

const createPost = async () => {
  try {
    const response = await gofetch.value.post('/posts', null, {
      title: 'GoFetch WASM Demo',
      body: 'This post was created using GoFetch compiled to WebAssembly!',
      userId: 1
    })
    currentResponse.value = response
  } catch (err) {
    console.error('Request failed:', err)
  }
}

const updatePost = async () => {
  try {
    const response = await gofetch.value.put('/posts/1', null, {
      id: 1,
      title: 'Updated via GoFetch WASM',
      body: 'This post was updated using PUT request',
      userId: 1
    })
    currentResponse.value = response
  } catch (err) {
    console.error('Request failed:', err)
  }
}

const deletePost = async () => {
  try {
    const response = await gofetch.value.delete('/posts/1')
    currentResponse.value = response
  } catch (err) {
    console.error('Request failed:', err)
  }
}
</script>

<style scoped>
* {
  box-sizing: border-box;
}

#app {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  color: #333;
}

header {
  text-align: center;
  margin-bottom: 40px;
  padding: 40px 20px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border-radius: 12px;
}

header h1 {
  margin: 0 0 10px 0;
  font-size: 2.5rem;
}

header p {
  margin: 0;
  opacity: 0.9;
  font-size: 1.1rem;
}

.loading {
  text-align: center;
  padding: 60px 20px;
}

.spinner {
  border: 4px solid #f3f3f3;
  border-top: 4px solid #667eea;
  border-radius: 50%;
  width: 50px;
  height: 50px;
  animation: spin 1s linear infinite;
  margin: 0 auto 20px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.error {
  background: #fee;
  border: 2px solid #fcc;
  border-radius: 8px;
  padding: 30px;
  text-align: center;
}

.container {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 24px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.card h2 {
  margin: 0 0 20px 0;
  color: #667eea;
  font-size: 1.5rem;
}

.button-group {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.btn-primary {
  background: #667eea;
  color: white;
}

.btn-info {
  background: #3498db;
  color: white;
}

.btn-success {
  background: #2ecc71;
  color: white;
}

.btn-warning {
  background: #f39c12;
  color: white;
}

.btn-danger {
  background: #e74c3c;
  color: white;
}

.btn-small {
  padding: 8px 16px;
  font-size: 12px;
}

.response {
  margin-top: 16px;
}

.response-meta {
  margin-bottom: 12px;
}

.badge {
  display: inline-block;
  background: #667eea;
  color: white;
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 14px;
  font-weight: 600;
}

.response-body {
  background: #f8f9fa;
  border: 1px solid #e9ecef;
  border-radius: 6px;
  padding: 16px;
  overflow-x: auto;
  font-size: 13px;
  line-height: 1.5;
}

.logs-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.logs-header h2 {
  margin: 0;
}

.logs {
  max-height: 400px;
  overflow-y: auto;
  border: 1px solid #e9ecef;
  border-radius: 6px;
  background: #f8f9fa;
}

.log-entry {
  padding: 12px 16px;
  border-bottom: 1px solid #e9ecef;
  font-size: 13px;
}

.log-entry:last-child {
  border-bottom: none;
}

.log-time {
  color: #6c757d;
  margin-right: 12px;
  font-weight: 600;
}

.log-message {
  color: #333;
}

.log-data {
  margin: 8px 0 0 0;
  padding: 8px;
  background: white;
  border-radius: 4px;
  font-size: 12px;
}

.log-success {
  background: #d4edda;
  border-left: 4px solid #28a745;
}

.log-error {
  background: #f8d7da;
  border-left: 4px solid #dc3545;
}

.log-info {
  background: #d1ecf1;
  border-left: 4px solid #17a2b8;
}

.empty-logs {
  padding: 40px;
  text-align: center;
  color: #6c757d;
  font-style: italic;
}

@media (max-width: 768px) {
  header h1 {
    font-size: 1.8rem;
  }
  
  .button-group {
    flex-direction: column;
  }
  
  .btn {
    width: 100%;
  }
}
</style>
